### ISSUE TITLE
Deprecate `color_type: label-card`?

### ISSUE THREAD

**Issue by RomRider** [custom-cards/button-card#107]
As per this comment
https://github.com/custom-cards/button-card/issues/104#issuecomment-485063371

Need to experiment a bit.

**Comment by SeanPM5** [comment]
That's an interesting idea.

I haven't tested it for several months, so I don't know if this has changed since then (or perhaps my config was wrong, because I was just getting started with Lovelace back then). But I believe the label-card is more limited compared to the normal buttons. 

I wanted to have a label-card that toggled an input_boolean to show/hide a conditional "light settings" card underneath it, as seen in this old screenshot of mine:

![image](https://i.imgur.com/IU60huz.png)

But I could never get it working. The label-card was not accepting any interaction or service calls, it was purely decorative if I remember correctly. So that might be something you want to look into. If that is still the case, it might be even more reason to deprecate it.

However if this gets removed, I think docs page should still have an example of how to "recreate" the appearance of it using `color_type: card`.

**Comment by RomRider** [comment]
I don't know before, but now the label card supports tap_action and hold_action. And in the next version, the code to render `color_type: card` and `color_type: label card` is exacte same.
If you define a button without entity, it's not going to display any icon, just the name you've set, or nothing if there's no name (as you did in #118)

**Comment by RomRider** [comment]
I don't know before, but now the label card supports tap_action and hold_action. And in the next version, the code to render `color_type: card` and `color_type: label card` is exacte same.
If you define a button without entity, it's not going to display any icon, just the name you've set, or nothing if there's no name (as you did in #118)
