### ISSUE TITLE
Feature Request: button height

### ISSUE THREAD

**Issue by jer78** [custom-cards/button-card#111]
There are times, the button doesn’t line up with other components when in a horizontal stack. It would be nice to manually set the height of the button in these cases. Also if using a few Buttons together in a horizontal stack they are too tall. You can shrink them by using blank buttons but it would be nice to have them horizontally take the full width and just manually reduce the height.

**Comment by VDRainer** [comment]
Couldn't this be made with style?
```
  style:
    - height: 40px
```

**Comment by iantrich** [comment]
This probably used to work, but since the last refactoring to make the button not depend on mwc or paper button, that is no longer true. It is only applied to the outer div, i.e. card, but not the inner icon or text.

@RomRider not sure how you want to approach this, but have three possible solutions I can think of off the top of my head:
1. Introduce `icon` and `text` style options (easy)
2. Revert to mwc-button (easy)
3. Implement CSS custom properties (most work and most limiting as you have to define each item you want to be customizable)

**Comment by RomRider** [comment]
@jer78, in the meantime, can you try something like that please?
```yaml
- type: custom:button-card
  size: 10%
  style:
    - padding: 5px 0px
   [rest of the config here] 
```

@iantrich, the mwc-button introduced more pain than solutions I think.
I like the idea to have icon and text styling options, it's just going to make the config even more complex :)

**Comment by iantrich** [comment]
Didn't say I liked the idea😉

**Comment by mrand** [comment]
Depending on how this could be done, it might resolve #15 as well.  Or not :-)

**Comment by RomRider** [comment]
Looking into this currently with the help of `display: grid`.
But CSS is really painful!!

**Comment by RomRider** [comment]
@mrand @jer78, would #132 satisfy your request?
