### ISSUE TITLE
Ellipsis adds 3px margin left

### ISSUE THREAD

**Issue by atterdal** [custom-cards/button-card#198]
**Checklist**
- [ x ] I updated the card to the latest version available
- [ x ] I cleared the cache of my browser

**Describe the bug**
When text overflows some mysterious margin is added to the left side.

**Version of the card**
Version: 1.11.1

**Screenshots**
<img width="268" alt="Skärmavbild 2019-07-18 kl  10 19 24" src="https://user-images.githubusercontent.com/2734444/61441338-b372e600-a945-11e9-94d3-e9306d646506.png">

**Comment by RomRider** [comment]
Hey, the solution to this problem is here: https://community.home-assistant.io/t/lovelace-button-card/65981/1678?u=romrider

Mainly this part:
You should add:
`- text-align: start`to all the fields and it will fix alignment issues.

Looks like when `ellipsis` is used, it doesn’t take into account the `justify-self`. But you still need to keep `justify-self`, because when it’s actually not “ellipsed”, it will use `justify-self`! CSS nightmare :)

**Comment by atterdal** [comment]
Awesome! Thanks.
