### ISSUE TITLE
Confirmation linked to actions

### ISSUE THREAD

**Issue by manonstreet** [custom-cards/button-card#217]
Please consider moving the confirmation option under Actions and allow the text to support templating.  This would allow the confirmation message to act like context aware documentation.

I am using tap and double tap actions, however the same confirmation dialog triggers regardless of the type of action invoked.  It would be useful and flexible to selectively allow (or disable) confirmation messages per action type.  If the field supported templating, the user could confirm the change in state (Are you sure you wish to **disable** the...)

**Comment by RomRider** [comment]
Sounds fair, I'll do that 👌

**Comment by Fredderic** [comment]
+1  I have tap action set to None, and am using hold and dbltap instead.

Was trying using lock, but I find this way is much better.

Speaking of which, confirmation on unlock…?  I presume the plan would be to add per-action confirmation as overrides to the card default…  however, since lock is a kind of confirmation in itself, the standard confirmation should probably be attached to unlock rather than the actions, when locking is used.  Per-action confirmations would still be attached to their individual action regardless.

This would allow:
- confirmation on all actions (current)
- customised or selective confirmations on some actions (this initial FR)
- confirmation on unlock before any actions are possible (this comment)
- all of the above, nothing stopping you putting the same confirmation on every action

**Comment by manonstreet** [comment]
Awesome.  Thanks!
