### ISSUE TITLE
No display for zero values

### ISSUE THREAD

**Issue by skyx3** [custom-cards/button-card#681]
Hi all, I use Button-Card. But if the value is currently 0, no value is displayed. Is there a trick to solve this? It would look better if it showed "0 km/h" when the wind is not blowing.

![grafik](https://user-images.githubusercontent.com/58375274/231259112-cf1f16fe-a0cf-4ff9-8389-3782559d9aee.png)

**Comment by Mariusthvdb** [comment]
no problem with button-card

<img width="353" alt="Scherm­afbeelding 2023-04-20 om 13 12 11" src="https://user-images.githubusercontent.com/33354141/233349337-77497a30-8698-44c6-800d-e16289bda943.png">

please close, and take it to the community, as you probably have a config that does not correctly configures what you want. If those are eve button-cards, because without config nobody can tell.
this repairs for bugs, the community is for questions, hop over to the custom:button-card pic please
