### ISSUE TITLE
Button Card Ended?

### ISSUE THREAD

**Issue by Ricks88** [custom-cards/button-card#717]
This mod seems no longer supported or updated. What happens when an author stops with a custom mod? Can others take the code and continue? Or can in a few months nobody use this anymore and can we change/delete all we made with it..

**Comment by Mariusthvdb** [comment]
no it has not ended.
As a matter of fact, Romrider updated all of his cards in April to be updated to the new and ever changing HA Dashboard considerations....

so, if anything, imho it would be best if the code owner here could find time to update some of the newer functionality (state translations and new action come to mind)

but other than that: its open source, anyone can click Clone repo, and adapt that new Repo to their liking...

my suggestion would be to do so in good correspondence with RomRider here, who has been the magician for so many of our desktops over the last couple of years!

**Comment by Ricks88** [comment]
Thanks for the info!
And how does the Pull Requests work?
These are fixes made by other people right? But i cant seem to find this changes/updates in the downloaded packages, do they need to be accepted by x number of people or how does this work? Or can we change this in the local code ourself 

Would be a small disaster of such big projects just end and can't be continued haha, i build my whole layout with custom buttoncard

**Comment by Mariusthvdb** [comment]
PR'scan only be merged if the code owner accepts (and merges) those.

there have been numerous 'fixes'  that in the end introduced issues elsewhere in the code, so its a good thing these are tested and scrutinized before being merged. RomRider is short in time, so that explains why several PR's are still open.

yes you can change in your local code, but since this is a condensed (minified) resource, that wont be very easy..

**Comment by Mariusthvdb** [comment]
Hi RomRider,

just as a FYI, on template-entity-row we had some issues on the state-color, which were fixed by @TheHolyRoger in https://github.com/thomasloven/lovelace-template-entity-row/pull/105 

Tbh, I dont think these are merged in the release template-entity-row resource by Thomas, so figured not might be of interest for when you have time to look at implementing state-color on button-card

**Comment by RomRider** [comment]
I've just pushed a beta version with several fixes (localization, lock position, colors matching HA). Please let me know if it works but it might generate some breaking change (especially the color fix...)

**Comment by Ricks88** [comment]
> I've just pushed a beta version with several fixes (localization, lock position, colors matching HA). Please let me know if it works but it might generate some breaking change (especially the color fix...)
> 
> If you see some bugs, please report in a new Issue :)

Thank you very much! will try tomorrow :D
